# Generated by Django 5.0.7 on 2026-05-07 01:44

import ai_content.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GenerationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=200)),
                ('objectives', models.TextField()),
                ('content_type', models.CharField(choices=[('module', 'Module'), ('quiz', 'Quiz'), ('both', 'Both')], default='both', max_length=10)),
                ('reference_file', models.FileField(blank=True, null=True, upload_to=ai_content.models._reference_file_path)),
                ('reference_text', models.TextField(blank=True)),
                ('model_key', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('complete', 'Complete'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('generated_module_id', models.PositiveIntegerField(blank=True, null=True)),
                ('generated_activity_id', models.CharField(blank=True, max_length=36, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
