# Generated by Django 5.0.7 on 2026-05-07 01:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_content', '0001_initial'),
        ('course', '0001_initial'),
        ('subject', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generationrequest',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_requests', to='subject.subject'),
        ),
        migrations.AddField(
            model_name='generationrequest',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_requests', to='course.term'),
        ),
    ]
