# Generated by Django 5.0.7 on 2026-05-07 01:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activity', '0001_initial'),
        ('course', '0002_initial'),
        ('subject', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeBookComponents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gradebook_name', models.CharField(blank=True, max_length=100, null=True)),
                ('gradebook_category', models.CharField(choices=[('Exam', 'Exam'), ('Participation/Attendance', 'Participation/Attendance'), ('Major Assessment', 'Major Assessment')], default='Exam', max_length=100)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gradebook_components', to='activity.activitytype')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gradebook_components', to='subject.subject')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gradebook_components', to=settings.AUTH_USER_MODEL)),
                ('term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gradebook_components', to='course.term')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityTypePercentage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activity_type_percentage', to='activity.activitytype')),
                ('gradebook_component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_type_percentages', to='gradebookcomponent.gradebookcomponents')),
            ],
        ),
        migrations.CreateModel(
            name='TermGradeBookComponents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('base_grade', models.IntegerField(default=0)),
                ('subjects', models.ManyToManyField(related_name='term_gradebook_components', to='subject.subject')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='term_gradebook_components', to=settings.AUTH_USER_MODEL)),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='term_gradebook_components', to='course.term')),
            ],
        ),
        migrations.CreateModel(
            name='TransmutationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transmutation_table_name', models.CharField(max_length=100)),
                ('min_grade', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max_grade', models.DecimalField(decimal_places=2, max_digits=5)),
                ('transmuted_value', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ['-max_grade', 'min_grade'],
                'unique_together': {('transmutation_table_name', 'min_grade', 'max_grade')},
            },
        ),
        migrations.CreateModel(
            name='GradeVisibilitySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_visible', models.BooleanField(default=False, help_text='If checked, students can view their grades for this subject/term')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_visibility_settings', to='subject.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_visibility_settings', to=settings.AUTH_USER_MODEL)),
                ('term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grade_visibility_settings', to='course.term')),
            ],
            options={
                'verbose_name': 'Grade Visibility Setting',
                'verbose_name_plural': 'Grade Visibility Settings',
                'unique_together': {('teacher', 'subject', 'term')},
            },
        ),
    ]
