# Generated by Django 5.0.7 on 2026-05-07 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradebookcomponent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradebookcomponents',
            name='gradebook_category',
            field=models.CharField(max_length=100),
        ),
    ]
