# Generated by Django 5.0.7 on 2026-05-07 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_initial'),
        ('gradebookcomponent', '0002_alter_gradebookcomponents_gradebook_category'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='activitytypepercentage',
            unique_together={('gradebook_component', 'activity_type')},
        ),
    ]
