# Generated by Django 5.0.7 on 2026-05-15 07:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0002_announcement_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Date of Announcement'),
        ),
    ]
