# Generated by Django 5.0.7 on 2026-05-07 01:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('graded', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('Present', 'Present'), ('Present_Online', 'Present_Online'), ('Late', 'Late'), ('Absent', 'Absent'), ('Excused', 'Excused')], max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Retake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retake_date', models.DateField(auto_now_add=True)),
                ('reason', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_name', models.CharField(choices=[('First Semester', 'First Semester'), ('Second Semester', 'Second Semester'), ('Third Semester', 'Third Semester'), ('Fourth Semester', 'Fourth Semester'), ('Summer', 'Summer')], max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('end_semester', models.BooleanField(default=False)),
                ('passing_grade', models.PositiveIntegerField(default=75)),
                ('grade_calculation_method', models.CharField(choices=[('Averaging', 'Averaging'), ('Term Percentage', 'Term Percentage')], default='averaging', max_length=50)),
                ('create_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('accepted', models.BooleanField(default=False)),
                ('invited_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentParticipationScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('max_score', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='SubjectEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_date', models.DateField(auto_now_add=True)),
                ('can_view_grade', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('enrolled', 'Enrolled'), ('dropped', 'Dropped'), ('completed', 'Completed'), ('administrative_drop', 'Administrative Drop')], default='enrolled', max_length=30)),
                ('drop_date', models.DateField(blank=True, null=True)),
                ('administrative_drop_date', models.DateField(blank=True, null=True)),
                ('is_active_semester', models.BooleanField(default=True)),
                ('student_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherAttendancePoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_name', models.CharField(choices=[('Prelim', 'Prelim'), ('Midterm', 'Midterm'), ('Pre-Final', 'Pre-Final'), ('Final Term', 'Final Term')], max_length=50)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
