# Generated by Django 5.0.7 on 2026-05-07 01:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('course', '0001_initial'),
        ('subject', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='subject.schedule'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendance',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='subject.subject'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attendances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendance',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='course.attendancestatus'),
        ),
        migrations.AddField(
            model_name='semester',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='semesters', to='accounts.department'),
        ),
        migrations.AddField(
            model_name='studentinvite',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject.subject'),
        ),
        migrations.AddField(
            model_name='studentparticipationscore',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentparticipationscore',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='subject.subject'),
        ),
        migrations.AddField(
            model_name='subjectenrollment',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='course.semester'),
        ),
        migrations.AddField(
            model_name='subjectenrollment',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subjectenrollment',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='subject.subject'),
        ),
        migrations.AddField(
            model_name='retake',
            name='subject_enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retakes', to='course.subjectenrollment'),
        ),
        migrations.AddField(
            model_name='teacherattendancepoints',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='course.attendancestatus'),
        ),
        migrations.AddField(
            model_name='teacherattendancepoints',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_points', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='term',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='term',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='course.semester'),
        ),
        migrations.AddField(
            model_name='studentparticipationscore',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='course.term'),
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(fields=('student', 'subject', 'date'), name='unique_attendance_per_day'),
        ),
        migrations.AddConstraint(
            model_name='subjectenrollment',
            constraint=models.UniqueConstraint(condition=models.Q(('student__isnull', False)), fields=('student', 'subject', 'semester'), name='uniq_student_subject_semester_with_student'),
        ),
        migrations.AddConstraint(
            model_name='subjectenrollment',
            constraint=models.UniqueConstraint(condition=models.Q(('student__isnull', True)), fields=('subject', 'semester'), name='uniq_subject_semester_when_placeholder'),
        ),
        migrations.AlterUniqueTogether(
            name='teacherattendancepoints',
            unique_together={('teacher', 'status')},
        ),
        migrations.AlterUniqueTogether(
            name='studentparticipationscore',
            unique_together={('student', 'subject', 'term')},
        ),
    ]
