"""
Django settings for lms project.

Generated by 'django-admin startproject' using Django 5.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path

from celery.schedules import crontab
from decouple import config
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# In production, DJANGO_SECRET_KEY must be set; the dev fallback is only used
# when DJANGO_DEBUG=true (i.e. local development).
DEBUG = os.getenv("DJANGO_DEBUG", "true").lower() in ("1", "true", "yes", "on")

_default_secret = "django-insecure-dev-only-do-not-use-in-prod"
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", _default_secret if DEBUG else "")
if not SECRET_KEY:
    raise RuntimeError("DJANGO_SECRET_KEY must be set when DJANGO_DEBUG is false.")

# Comma-separated hostnames, e.g. "classedge.hccci.edu.ph,127.0.0.1"
ALLOWED_HOSTS = [
    h.strip()
    for h in os.getenv(
        "DJANGO_ALLOWED_HOSTS",
        "*" if DEBUG else "",
    ).split(",")
    if h.strip()
]

# Production-only security headers / cookie flags. Skipped in DEBUG so local
# HTTP development still works.
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    X_FRAME_OPTIONS = "DENY"
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_REFERRER_POLICY = "same-origin"

DATA_UPLOAD_MAX_NUMBER_FIELDS = 10000

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.humanize",
    "accounts",
    "roles",
    "subject",
    "calendars",
    "module",
    "course",
    "message",
    "activity",
    "gradebookcomponent",
    "logs",
    "classroom",
    "social_media",
    "coil",
    "mobile",
    "rms",
    "django.contrib.sites",
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.microsoft",
    "allauth.socialaccount.providers.google",
    "django_summernote",
    "rest_framework",
    "rest_framework_simplejwt",
    "multiselectfield",
    "tinymce",
    "channels",
    "corsheaders",
    "captcha",
    "django_recaptcha",
    "rest_framework_simplejwt.token_blacklist",
    "easyaudit",
    "drf_standardized_errors",
    "central_content",
    "received_central_content",
    "ai_content",
    "rag_tutor",
    "at_risk",
    "gamification",
    "ide",
    "stress_tests",
    "migration",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "allauth.account.middleware.AccountMiddleware",
    "accounts.middleware.LegalConsentRequiredMiddleware",
    "easyaudit.middleware.easyaudit.EasyAuditMiddleware",
]

DJANGO_EASY_AUDIT_UNREGISTERED_CLASSES_EXTRA = [
    "socialaccount.SocialAccount",
    "socialaccount.SocialToken",
    "socialaccount.SocialApp",
    "account.EmailAddress",
    "account.EmailConfirmation",
]

ROOT_URLCONF = "lms.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "rag_tutor.context_processors.rag_tutor_flags",
                "message.context_processors.unread_messages_count",
                "message.context_processors.unread_notifications_count",
                "message.context_processors.pending_friend_requests_count",
                # [Classedge LMS] Removed: logs.context_processors.subject_logs
                # previously overwrote `notifications` and `unread_notifications_count`
                # with a different shape (read/url instead of is_read/link),
                # which broke the bell popover's link rendering and read-flip
                # behavior. Its responsibilities (subject-scoping the logs and
                # honoring UserSubjectLog.read) have been merged into
                # message.context_processors.unread_notifications_count.
                "roles.context_processors.school_name",
                "roles.context_processors.school_name",
                "django.template.context_processors.media",
                "accounts.context_processors.school_context",
                "accounts.context_processors.logo_update_time",
                "accounts.context_processors.department_context",
                "accounts.context_processors.legal_modal_context",
                "accounts.context_processors.quick_action_subjects",
                "gamification.context_processors.student_context",
            ],
        },
    },
]


WSGI_APPLICATION = "lms.wsgi.application"

CORS_ALLOW_ALL_ORIGINS = True

# CORS_TRUSTED_ORIGINS = [
#     "http://127.0.0.1",
#     "https://172.16.30.236:7000"
# ]

# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases


# Environment-driven: SQLite for local dev (default), PostgreSQL in production
# via DB_* env vars. No credentials are hardcoded here — set them in .env.
ENVIRONMENT = os.getenv("ENVIRONMENT", "development")

if ENVIRONMENT == "production":
    DATABASES = {
        "default": {
            "ENGINE": os.getenv("DB_ENGINE", "django.db.backends.postgresql"),
            "NAME": os.getenv("DB_NAME", ""),
            "USER": os.getenv("DB_USER", ""),
            "PASSWORD": os.getenv("DB_PASSWORD", ""),
            "HOST": os.getenv("DB_HOST", "localhost"),
            "PORT": os.getenv("DB_PORT", "5432"),
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
            "OPTIONS": {
                "timeout": 30,
            },
        }
    }

ASGI_APPLICATION = "lms.asgi.application"

CHANNEL_LAYERS = {"default": {"BACKEND": "channels.layers.InMemoryChannelLayer"}}

# CORS_ALLOWED_ORIGINS = [
#     "https://hccci.edu.ph",
# ]

# CSRF_TRUSTED_ORIGINS = [
#     "https://hccci.edu.ph",
#     "http://hccci.edu.ph",
#     "https://hccci.edu.ph",
# ]

CORS_ALLOW_CREDENTIALS = True


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Asia/Manila"

USE_I18N = True

USE_TZ = True

MEDIA_ROOT = os.path.join(BASE_DIR, "media")
MEDIA_URL = "/media/"

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = "static/"

STATICFILES_DIRS = [BASE_DIR / "static"]

# SAMEORIGIN is acceptable for dev (e.g. summernote iframes); production
# tightens to DENY in the security block near the top of this file.
X_FRAME_OPTIONS = "DENY" if not DEBUG else "SAMEORIGIN"

STATIC_ROOT = BASE_DIR / "staticfiles"

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


SITE_ID = 1

AUTH_USER_MODEL = "accounts.CustomUser"

AUTHENTICATION_BACKENDS = (
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
)


LOGIN_REDIRECT_URL = "/dashboard/"
LOGOUT_REDIRECT_URL = "/admin_login_view/"
LOGIN_URL = "admin_login_view"

SOCIALACCOUNT_PROVIDERS = {
    "microsoft": {
        "APP": {
            "client_id": os.getenv("MICROSOFT_CLIENT_ID", ""),
            "secret": os.getenv("MICROSOFT_SECRET", ""),
            "key": "",
        },
        "AUTH_PARAMS": {
            "response_type": "code",
        },
        "SCOPE": [
            "openid",
            "email",
            "profile",
            "offline_access",
            "User.Read",
            "OnlineMeetings.ReadWrite",
            "Calendars.ReadWrite",
        ],
        "TENANT": os.getenv("MICROSOFT_TENANT", ""),
    }
}

# Auto-link Microsoft logins to existing local users when emails match.
SOCIALACCOUNT_EMAIL_AUTHENTICATION = True
SOCIALACCOUNT_EMAIL_AUTHENTICATION_AUTO_CONNECT = True
SOCIALACCOUNT_EMAIL_VERIFICATION = "none"  # Microsoft verifies email already.
SOCIALACCOUNT_AUTO_SIGNUP = True  # Skip allauth's signup confirmation page.

MS_TENANT_ID = os.getenv("MICROSOFT_TENANT")
MS_CLIENT_ID = os.getenv("MICROSOFT_CLIENT_ID")
MS_CLIENT_SECRET = os.getenv("MICROSOFT_SECRET")

# Toggle the OneDrive upload + embed integration. When False, file uploads
# are stored locally only — useful for dev/CI where the Azure app may not
# have Files.ReadWrite.All consent yet.
ONEDRIVE_UPLOAD_ENABLED = os.getenv("ONEDRIVE_UPLOAD_ENABLED", "true").lower() == "true"
ONEDRIVE_UPLOAD_FOLDER = os.getenv("ONEDRIVE_UPLOAD_FOLDER", "ClassEdge")
# UPN (email address) of the service account whose OneDrive will store all
# uploaded Office files. The Azure app uses its application credentials
# (Files.ReadWrite.All) to write here — no per-user OAuth token needed.
ONEDRIVE_SERVICE_ACCOUNT_UPN = os.getenv("ONEDRIVE_SERVICE_ACCOUNT_UPN", "")
# Extensions we route through OneDrive for embeddable preview. Office formats
# only — everything else stays purely local.
ONEDRIVE_PREVIEW_EXTS = {".ppt", ".pptx", ".doc", ".docx", ".xls", ".xlsx"}

RMS_TOKEN = os.getenv("RMS_TOKEN")
RMS_URL = os.getenv("RMS_URL")


FACEBOOK_PAGE_ID = config("FACEBOOK_PAGE_ID", default="").strip()
FACEBOOK_ACCESS_TOKEN = config("FACEBOOK_KEY")


CLOUDCONVERT_API_KEY = os.getenv("CLOUDCONVERT_API_KEY", "")

CENTRAL_INGEST_TOKEN = os.getenv("CENTRAL_INGEST_TOKEN", "")

MINERU_SERVICE_URL = os.getenv("MINERU_SERVICE_URL", "http://localhost:8765")
MINERU_TOC_TIMEOUT = int(os.getenv("MINERU_TOC_TIMEOUT", "120"))
MINERU_CHAPTER_TIMEOUT = int(os.getenv("MINERU_CHAPTER_TIMEOUT", "300"))

SOCIALACCOUNT_LOGIN_ON_GET = True

# Additional allauth settings
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_EMAIL_VERIFICATION = "none"  # can be "mandatory", "optional", or "none"
# allauth ≥0.56 replaced ACCOUNT_LOGIN_ATTEMPTS_LIMIT/TIMEOUT with rate-limit rules.
# 5 failed attempts per 300s window (same effective behavior as before).
ACCOUNT_RATE_LIMITS = {
    "login_failed": "5/300s",
}

# Additional settings
ACCOUNT_AUTHENTICATION_METHOD = "username_email"
ACCOUNT_USERNAME_REQUIRED = True
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_SIGNUP_EMAIL_ENTER_TWICE = True
ACCOUNT_SESSION_REMEMBER = None
ACCOUNT_SIGNUP_PASSWORD_ENTER_TWICE = True
ACCOUNT_USERNAME_MIN_LENGTH = 4
ACCOUNT_EMAIL_CONFIRMATION_EXPIRE_DAYS = 3
ACCOUNT_EMAIL_SUBJECT_PREFIX = "[lms] "

CELERY_BROKER_URL = config("CELERY_BROKER_URL", default="redis://localhost:6379/0")
CELERY_RESULT_BACKEND = config(
    "CELERY_RESULT_BACKEND", default="redis://localhost:6379/0"
)


ACCOUNT_ADAPTER = "accounts.utils.adapter_utils.CustomAccountAdapter"
SOCIALACCOUNT_ADAPTER = "accounts.utils.adapter_utils.CustomSocialAccountAdapter"

SESSION_ENGINE = "django.contrib.sessions.backends.db"
SESSION_COOKIE_AGE = 1209600


EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = config("EMAIL_HOST", default="smtp.office365.com")
EMAIL_PORT = config("EMAIL_PORT", default=587, cast=int)
EMAIL_USE_TLS = config("EMAIL_USE_TLS", default=True, cast=bool)
EMAIL_HOST_USER = config("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = config("EMAIL_HOST_PASSWORD")
DEFAULT_FROM_EMAIL = config("DEFAULT_FROM_EMAIL", default="lms@hccci.edu.ph")

BASE_URL = config("BASE_URL")

SCHOOL_NAME = config("SCHOOL_NAME", default="Default School Name")
SCHOOL_SHORT_NAME = config("SCHOOL_SHORT_NAME", default="Default School Short Name")


GOOGLE_API_KEY = config("API_KEY")

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ),
    "DEFAULT_RENDERER_CLASSES": (
        "djangorestframework_camel_case.render.CamelCaseJSONRenderer",
        "djangorestframework_camel_case.render.CamelCaseBrowsableAPIRenderer",
    ),
    "DEFAULT_PARSER_CLASSES": (
        "djangorestframework_camel_case.parser.CamelCaseFormParser",
        "djangorestframework_camel_case.parser.CamelCaseMultiPartParser",
        "djangorestframework_camel_case.parser.CamelCaseJSONParser",
    ),
    "EXCEPTION_HANDLER": "drf_standardized_errors.handler.exception_handler",
}

DRF_STANDARDIZED_ERRORS = {
    "EXCEPTION_FORMATTER_CLASS": "drf_standardized_errors.formatter.ExceptionFormatter",
    "ENABLE_IN_DEBUG_FOR_UNHANDLED_EXCEPTIONS": True,
}

# Define paths to your keys
PRIVATE_KEY_PATH = BASE_DIR / "jwtRS256.key"
PUBLIC_KEY_PATH = BASE_DIR / "jwtRS256.key.pub"

# Read the content of the files
# We use .read_text() to get the string format required by most JWT libraries
with open(PRIVATE_KEY_PATH, "r") as f:
    RS256_PRIVATE_KEY = f.read()

with open(PUBLIC_KEY_PATH, "r") as f:
    RS256_PUBLIC_KEY = f.read()

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=15),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=30),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "UPDATE_LAST_LOGIN": False,
    "ALGORITHM": "RS256",
    "SIGNING_KEY": RS256_PRIVATE_KEY,  # Uses your Django SECRET_KEY
    "VERIFYING_KEY": RS256_PUBLIC_KEY,
    "AUDIENCE": None,
    "ISSUER": None,
    "AUTH_HEADER_TYPES": ("Bearer",),
    "AUTH_HEADER_NAME": "HTTP_AUTHORIZATION",
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
    "AUTH_TOKEN_CLASSES": ("rest_framework_simplejwt.tokens.AccessToken",),
    "TOKEN_TYPE_CLAIM": "token_type",
    "JTI_CLAIM": "jti",
    "SLIDING_TOKEN_REFRESH_EXP_CLAIM": "refresh_exp",
    "SLIDING_TOKEN_LIFETIME": timedelta(minutes=5),
    "SLIDING_TOKEN_REFRESH_LIFETIME": timedelta(days=1),
}

# Google reCAPTCHA v3 Keys
RECAPTCHA_PUBLIC_KEY = config("RECAPTCHA_PUBLIC_KEY")
RECAPTCHA_PRIVATE_KEY = config("RECAPTCHA_PRIVATE_KEY")
RECAPTCHA_REQUIRED_SCORE = 0.5

# Reverse proxy configuration
USE_X_FORWARDED_HOST = True
USE_X_FORWARDED_PORT = True
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")


# Celery Configuration

CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = "Asia/Manila"  # Or your timezone
CELERY_ENABLE_UTC = True
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60  # 30 minutes (30 * 60)

ONE_SIGNAL_APP_ID = config("ONE_SIGNAL_APP_ID")
ONE_SIGN_API_KEY = config("ONE_SIGN_API_KEY")
ORGANIZATION_API_KEY = config("ORGANIZATION_API_KEY")
ONE_SIGNAL_ANDROID_CHANNEL_ID = config("ONE_SIGNAL_ANDROID_CHANNEL_ID", default="")

CELERY_BEAT_SCHEDULE = {
    # RMS Sync - Run once daily at 2 AM
    # 'sync-rms-data-daily': {
    #     'task': 'rms.tasks.sync_all_rms_data',  # We'll create this
    #     'schedule': crontab(hour=2, minute=0),  # Every day at 2:00 AM
    # },
    # Alternative: Run every 24 hours from when worker starts
    "sync-rms-data-daily": {
        "task": "rms.tasks.sync_all_rms_data",
        "schedule": 86400.0,  # 86400 seconds = 24 hours
    },
    # Auto-finalize expired student activity attempts every 5 minutes so
    # students who closed the browser still get their autosaved answers
    # graded once the timer (and any late-submission grace window) ends.
    "finalize-expired-activity-attempts": {
        "task": "activity.tasks.finalize_expired_attempts",
        "schedule": 300.0,  # seconds
    },
    # Self-attendance: every 5 minutes, mark Absent any enrolled students who
    # didn't self-check-in for a class whose schedule window just ended.
    "mark-absent-for-ended-classes": {
        "task": "course.tasks.mark_absent_for_ended_classes",
        "schedule": 300.0,  # seconds
    },
    # Deadline reminders: hourly, notify enrolled students of activities due
    # within the next 48h that they haven't started yet. The command dedupes
    # per (student, activity) inside the 48h window, so an hourly tick reminds
    # each upcoming deadline once rather than every hour.
    "notify-due-soon": {
        "task": "logs.tasks.notify_due_soon",
        "schedule": 3600.0,  # seconds (hourly)
        "kwargs": {"hours": 48},
    },
    # Streak-protection: once daily at 5 PM Manila (crontab honours
    # CELERY_TIMEZONE), nudge students whose login streak will break unless
    # they log in today — while there's still time to act. Deduped per student
    # per day by the command's notify() window.
    "notify-streak-at-risk": {
        "task": "gamification.tasks.notify_streak_at_risk",
        "schedule": crontab(hour=17, minute=0),
    },
    # Migration pipeline tick — orchestrates old-LMS data pull. Gated by
    # MIGRATION_ENABLED setting; the task is a no-op when that is False, so
    # this schedule is safe to leave registered in non-migrating environments.
    "migration-pipeline-tick": {
        "task": "migration.tasks.run_migration_pipeline",
        "schedule": float(os.environ.get("MIGRATION_BATCH_INTERVAL_SECONDS", "30")),
    },
}


# AI Content Generation (Prime tier)
AI_CONTENT_MODELS = {
    "haiku": {
        "provider": "anthropic",
        "model": "claude-haiku-4-5-20251001",
        "api_key_env": "ANTHROPIC_API_KEY",
    },
    "sonnet": {
        "provider": "anthropic",
        "model": "claude-sonnet-4-6",
        "api_key_env": "ANTHROPIC_API_KEY",
    },
}
AI_CONTENT_DEFAULT_MODEL = "haiku"

# RAG Tutor
RAG_TUTOR_EMBEDDING_MODEL = "text-embedding-3-small"
RAG_TUTOR_LLM_MODEL = "claude-haiku-4-5-20251001"
RAG_TUTOR_TOP_K = 5
RAG_TUTOR_RELEVANCE_THRESHOLD = 0.8
# Tutor UI is gated on both API keys being present — embedding (OpenAI) for
# indexing/querying, generation (Anthropic) for answering. Either missing
# means the feature isn't ready, so the chat bubble stays hidden.
RAG_TUTOR_AVAILABLE = bool(os.environ.get("OPENAI_API_KEY")) and bool(
    os.environ.get("ANTHROPIC_API_KEY")
)

# At-risk Dashboard
AT_RISK_WEIGHTS = {
    "grade": 0.0,
    "completion": 0.0,
    "attendance": 1.0,
}
AT_RISK_HIGH_THRESHOLD = 40
AT_RISK_MEDIUM_THRESHOLD = 65

# Gamification
GAMIFICATION_XP_RATES = {
    "submission": 50,
    "early_submission": 75,
    "score_90": 30,
    "score_75": 15,
    "daily_login": 5,
    "perfect_attendance_week": 50,
}
GAMIFICATION_STREAK_FREEZE_MONTHLY = 1

# IDE / Judge0
JUDGE0_API_URL = os.getenv("JUDGE0_API_URL", "http://localhost:2358")
JUDGE0_API_KEY = os.getenv("JUDGE0_API_KEY", "")

from migration.settings_defaults import apply as _apply_migration_defaults

_apply_migration_defaults(globals())
