# Generated by Django 5.0.7 on 2026-05-15 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='onedrive_embed_url',
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='onedrive_item_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
