# Generated by Django 5.0.7 on 2026-05-25 08:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0003_module_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
