# Generated by Django 5.0.7 on 2026-05-07 01:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activity', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodingExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('python', 'Python'), ('javascript', 'JavaScript')], max_length=20)),
                ('starter_code', models.TextField(blank=True)),
                ('solution_code', models.TextField(blank=True)),
                ('test_cases', models.JSONField()),
                ('time_limit_seconds', models.PositiveSmallIntegerField(default=5)),
                ('memory_limit_kb', models.PositiveIntegerField(default=256000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coding_exercise', to='activity.activity')),
            ],
        ),
        migrations.CreateModel(
            name='CodeSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField()),
                ('language', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('error', 'Error')], default='pending', max_length=20)),
                ('result_json', models.JSONField(default=dict)),
                ('score', models.FloatField(null=True)),
                ('execution_time_ms', models.PositiveIntegerField(null=True)),
                ('memory_used_kb', models.PositiveIntegerField(null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_submissions', to=settings.AUTH_USER_MODEL)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ide.codingexercise')),
            ],
            options={
                'indexes': [models.Index(fields=['student', 'exercise'], name='ide_codesub_student_4510c0_idx'), models.Index(fields=['status'], name='ide_codesub_status_6cbf12_idx')],
            },
        ),
    ]
