# Generated by Django 5.0.7 on 2026-05-12 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ide', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codingexercise',
            name='language',
            field=models.CharField(choices=[('python', 'Python'), ('javascript', 'JavaScript'), ('typescript', 'TypeScript'), ('java', 'Java'), ('c', 'C'), ('cpp', 'C++'), ('csharp', 'C#'), ('go', 'Go'), ('rust', 'Rust'), ('ruby', 'Ruby'), ('php', 'PHP'), ('kotlin', 'Kotlin'), ('swift', 'Swift'), ('shell', 'Bash'), ('sql', 'SQL'), ('r', 'R'), ('lua', 'Lua')], max_length=20),
        ),
    ]
