# Generated by Django 5.0.7 on 2026-05-21 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_schoolname_brand_color'),
        ('accounts', '0009_profile_share_fields'),
    ]

    operations = [
    ]
