# Generated by Django 5.0.7 on 2026-06-01 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_merge_20260521_0818'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='seen_tours',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
