# Generated by Django 5.0.7 on 2026-05-07 01:44

import django.db.models.deletion
import received_central_content.models.received_module
import received_central_content.models.received_subject
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activity', '0001_initial'),
        ('subject', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceivedCentralSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('central_id', models.IntegerField(unique=True)),
                ('central_version', models.PositiveIntegerField()),
                ('subject_name', models.CharField(max_length=200)),
                ('subject_descriptive_title', models.CharField(blank=True, max_length=100)),
                ('subject_short_name', models.CharField(blank=True, max_length=30)),
                ('subject_photo', models.ImageField(blank=True, null=True, upload_to=received_central_content.models.received_subject._received_subject_photo_path)),
                ('subject_description', models.TextField(blank=True)),
                ('subject_code', models.CharField(blank=True, max_length=30)),
                ('subject_type', models.CharField(blank=True, max_length=10)),
                ('unit', models.PositiveIntegerField(default=3)),
                ('target_grade_level', models.CharField(blank=True, max_length=50)),
                ('target_curriculum', models.CharField(blank=True, max_length=100)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('last_received_at', models.DateTimeField(auto_now=True)),
                ('target_sdgs', models.ManyToManyField(blank=True, related_name='received_central_subjects', to='subject.sdg')),
            ],
            options={
                'db_table': 'received_central_subject',
                'ordering': ['-last_received_at'],
            },
        ),
        migrations.CreateModel(
            name='ReceivedCentralModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('central_id', models.IntegerField(unique=True)),
                ('file_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to=received_central_content.models.received_module._received_module_file_path)),
                ('url', models.URLField(blank=True, max_length=1500)),
                ('iframe_code', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('received_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='received_central_content.receivedcentralsubject')),
            ],
            options={
                'db_table': 'received_central_module',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ReceivedCentralActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('central_id', models.IntegerField(unique=True)),
                ('activity_name', models.CharField(max_length=100)),
                ('activity_instruction', models.TextField(blank=True)),
                ('max_score', models.PositiveIntegerField(default=100)),
                ('time_duration', models.PositiveIntegerField(default=0)),
                ('passing_score', models.FloatField(default=0)),
                ('passing_score_type', models.CharField(choices=[('number', 'Number'), ('percentage', 'Percentage')], default='percentage', max_length=10)),
                ('max_retake', models.PositiveIntegerField(default=0)),
                ('retake_method', models.CharField(choices=[('highest', 'Highest Score'), ('latest', 'Latest Take'), ('average', 'Average'), ('first', 'First Attempt')], default='highest', max_length=15)),
                ('shuffle_questions', models.BooleanField(default=False)),
                ('is_graded', models.BooleanField(default=True)),
                ('activity_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_central_activities', to='activity.activitytype')),
                ('related_modules', models.ManyToManyField(blank=True, related_name='related_activities', to='received_central_content.receivedcentralmodule')),
                ('received_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='received_central_content.receivedcentralsubject')),
            ],
            options={
                'db_table': 'received_central_activity',
                'ordering': ['central_id'],
            },
        ),
    ]
