# Generated by Django 5.0.7 on 2026-05-15 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0004_relabel_participation_to_major_assessment'),
        ('mobile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='activity_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to='activity.activityquestion'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='question_choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to='activity.questionchoice'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='student_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to='activity.studentquestion'),
        ),
    ]
