# Generated by Django 5.0.7 on 2026-05-07 01:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoilPartnerSchool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=255)),
                ('school_domain', models.CharField(help_text='e.g. hccci.edu.ph', max_length=255)),
                ('student_participating', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('Pending Acceptance', 'Pending Acceptance'), ('Partner', 'Partner'), ('Rejected', 'Rejected'), ('Send Invite', 'Send Invite')], default='Send Invite', max_length=20)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_person', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('school_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('invite_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('date_registered', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
