# Generated by Django 5.0.7 on 2026-05-07 01:44

import central_content.models.central_module
import central_content.models.central_subject
import central_content.models.parsed_textbook
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activity', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CentralStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('full_name', models.CharField(max_length=150)),
                ('role', models.CharField(choices=[('editor', 'Editor'), ('reviewer', 'Reviewer'), ('publisher', 'Publisher')], max_length=20)),
                ('password', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'central_content_staff',
                'ordering': ['email'],
            },
        ),
        migrations.CreateModel(
            name='ContentGenerationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_key', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('complete', 'Complete'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('total_weeks', models.PositiveIntegerField()),
                ('completed_weeks', models.PositiveIntegerField(default=0)),
                ('failed_weeks', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('week_results', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'central_content_generation_job',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CurriculumPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_subject_id', models.PositiveIntegerField()),
                ('session_count', models.PositiveIntegerField()),
                ('minutes_per_session', models.PositiveIntegerField()),
                ('model_key', models.CharField(max_length=50)),
                ('plan_data', models.JSONField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'central_content_curriculum_plan',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ParsedChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('start_page', models.PositiveIntegerField()),
                ('end_page', models.PositiveIntegerField()),
                ('parsed_data', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('parsing', 'Parsing'), ('complete', 'Complete'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'central_content_parsed_chapter',
                'ordering': ['chapter_number'],
            },
        ),
        migrations.CreateModel(
            name='ParsedTextbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('original_file', models.FileField(upload_to=central_content.models.parsed_textbook._textbook_file_path)),
                ('file_hash', models.CharField(blank=True, max_length=64)),
                ('toc_data', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('uploading', 'Uploading'), ('parsing_toc', 'Parsing TOC'), ('toc_ready', 'TOC Ready'), ('failed', 'Failed')], default='uploading', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'central_content_parsed_textbook',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PushJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('push', 'Push'), ('delete', 'Delete')], max_length=10)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], max_length=10)),
                ('subject_version', models.PositiveIntegerField()),
                ('http_status', models.IntegerField(blank=True, null=True)),
                ('response_body', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'central_content_push_job',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('base_url', models.URLField()),
                ('api_token', models.CharField(max_length=80)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'central_content_school',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SchoolSubjectBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_subject_id', models.IntegerField()),
                ('school_subject_name', models.CharField(max_length=200)),
                ('school_subject_code', models.CharField(blank=True, max_length=30)),
                ('pushed_version', models.PositiveIntegerField(blank=True, null=True)),
                ('last_pushed_at', models.DateTimeField(blank=True, null=True)),
                ('bound_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'central_content_school_subject_binding',
                'ordering': ['target_school', 'central_subject'],
            },
        ),
        migrations.CreateModel(
            name='CentralModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to=central_content.models.central_module._module_file_path)),
                ('url', models.URLField(blank=True, max_length=1500)),
                ('iframe_code', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In Review'), ('approved', 'Approved')], default='draft', max_length=20)),
                ('review_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='modules_created', to='central_content.centralstaff')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modules_reviewed', to='central_content.centralstaff')),
            ],
            options={
                'db_table': 'central_content_module',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CentralActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(max_length=100)),
                ('activity_instruction', models.TextField(blank=True)),
                ('max_score', models.PositiveIntegerField(default=100)),
                ('time_duration', models.PositiveIntegerField(default=0)),
                ('passing_score', models.FloatField(default=0)),
                ('passing_score_type', models.CharField(choices=[('number', 'Number'), ('percentage', 'Percentage')], default='percentage', max_length=10)),
                ('max_retake', models.PositiveIntegerField(default=0)),
                ('retake_method', models.CharField(choices=[('highest', 'Highest Score'), ('latest', 'Latest Take'), ('average', 'Average'), ('first', 'First Attempt')], default='highest', max_length=15)),
                ('shuffle_questions', models.BooleanField(default=False)),
                ('is_graded', models.BooleanField(default=True)),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In Review'), ('approved', 'Approved')], default='draft', max_length=20)),
                ('review_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='activity.activitytype')),
                ('related_modules', models.ManyToManyField(blank=True, related_name='related_activities', to='central_content.centralmodule')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activities_created', to='central_content.centralstaff')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities_reviewed', to='central_content.centralstaff')),
            ],
            options={
                'db_table': 'central_content_activity',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('from_state', models.CharField(max_length=20)),
                ('to_state', models.CharField(max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_entries', to='central_content.centralstaff')),
            ],
            options={
                'db_table': 'central_content_audit_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CentralSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=200)),
                ('subject_descriptive_title', models.CharField(blank=True, max_length=100)),
                ('subject_short_name', models.CharField(blank=True, max_length=30)),
                ('subject_photo', models.ImageField(blank=True, null=True, upload_to=central_content.models.central_subject._subject_photo_path)),
                ('subject_description', models.TextField(blank=True)),
                ('subject_code', models.CharField(blank=True, max_length=30)),
                ('subject_type', models.CharField(blank=True, choices=[('Lec', 'Lec'), ('Lab', 'Lab')], max_length=10)),
                ('unit', models.PositiveIntegerField(default=3)),
                ('target_grade_level', models.CharField(blank=True, max_length=50)),
                ('target_curriculum', models.CharField(blank=True, max_length=100)),
                ('version', models.PositiveIntegerField(default=1)),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In Review'), ('approved', 'Approved')], default='draft', max_length=20)),
                ('review_notes', models.TextField(blank=True)),
                ('source_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subjects_created', to='central_content.centralstaff')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects_reviewed', to='central_content.centralstaff')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects_submitted', to='central_content.centralstaff')),
            ],
            options={
                'db_table': 'central_content_subject',
                'ordering': ['-updated_at'],
            },
        ),
    ]
