# Generated by Django 5.0.7 on 2026-05-07 01:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('central_content', '0001_initial'),
        ('subject', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='centralsubject',
            name='target_sdgs',
            field=models.ManyToManyField(blank=True, related_name='central_subjects', to='subject.sdg'),
        ),
        migrations.AddField(
            model_name='centralmodule',
            name='central_subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='central_content.centralsubject'),
        ),
        migrations.AddField(
            model_name='centralactivity',
            name='central_subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='central_content.centralsubject'),
        ),
        migrations.AddField(
            model_name='contentgenerationjob',
            name='triggered_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='content_generation_jobs', to='central_content.centralstaff'),
        ),
        migrations.AddField(
            model_name='curriculumplan',
            name='generated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='curriculum_plans', to='central_content.centralstaff'),
        ),
        migrations.AddField(
            model_name='contentgenerationjob',
            name='curriculum_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_jobs', to='central_content.curriculumplan'),
        ),
        migrations.AddField(
            model_name='parsedtextbook',
            name='central_subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='textbooks', to='central_content.centralsubject'),
        ),
        migrations.AddField(
            model_name='parsedtextbook',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='textbooks_uploaded', to='central_content.centralstaff'),
        ),
        migrations.AddField(
            model_name='parsedchapter',
            name='textbook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='central_content.parsedtextbook'),
        ),
        migrations.AddField(
            model_name='curriculumplan',
            name='textbook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='central_content.parsedtextbook'),
        ),
        migrations.AddField(
            model_name='pushjob',
            name='central_subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_jobs', to='central_content.centralsubject'),
        ),
        migrations.AddField(
            model_name='pushjob',
            name='triggered_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='push_jobs_triggered', to='central_content.centralstaff'),
        ),
        migrations.AddField(
            model_name='school',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schools_created', to='central_content.centralstaff'),
        ),
        migrations.AddField(
            model_name='pushjob',
            name='target_school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_jobs', to='central_content.school'),
        ),
        migrations.AddField(
            model_name='schoolsubjectbinding',
            name='bound_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bindings_created', to='central_content.centralstaff'),
        ),
        migrations.AddField(
            model_name='schoolsubjectbinding',
            name='central_subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_bindings', to='central_content.centralsubject'),
        ),
        migrations.AddField(
            model_name='schoolsubjectbinding',
            name='target_school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bindings', to='central_content.school'),
        ),
        migrations.AddIndex(
            model_name='auditlogentry',
            index=models.Index(fields=['content_type', 'object_id'], name='central_con_content_99123c_idx'),
        ),
        migrations.AddConstraint(
            model_name='schoolsubjectbinding',
            constraint=models.UniqueConstraint(fields=('central_subject', 'target_school'), name='uniq_central_subject_target_school'),
        ),
    ]
