# Generated by Django 5.0.7 on 2026-05-07 01:44

import classroom.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom_mode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_classroom_mode', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Screenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=classroom.models.get_upload_path)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher_Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_started', models.DateTimeField()),
                ('time_ended', models.DateTimeField(blank=True, null=True)),
                ('manual_ended', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('celery_task_id', models.CharField(blank=True, help_text='Celery task ID for auto-ending class', max_length=255, null=True)),
            ],
        ),
    ]
