# Generated by Django 5.0.7 on 2026-05-07 01:44

import activity.models.activity_model
import activity.models.retake_models
import activity.models.student_activity_model
import cuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('activity_name', models.CharField(max_length=100)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('show_score', models.BooleanField(default=False)),
                ('remedial', models.BooleanField(default=False)),
                ('max_retake', models.PositiveIntegerField(default=0)),
                ('time_duration', models.PositiveIntegerField(default=0)),
                ('max_score', models.PositiveIntegerField(blank=True, default=100, null=True)),
                ('status', models.BooleanField(default=True)),
                ('passing_score', models.FloatField(default=0)),
                ('passing_score_type', models.CharField(choices=[('number', 'Number'), ('percentage', 'Percentage')], default='percentage', max_length=10)),
                ('retake_method', models.CharField(choices=[('highest', 'Highest Score'), ('latest', 'Latest Take'), ('average', 'Average'), ('first', 'First Attempt')], default='highest', max_length=15)),
                ('activity_instruction', models.TextField(blank=True, null=True)),
                ('activity_file_instruction', models.FileField(blank=True, null=True, upload_to=activity.models.activity_model.get_upload_activity_file_instruction)),
                ('classroom_mode', models.BooleanField(default=False)),
                ('allow_late_submission', models.BooleanField(default=False)),
                ('late_submission_days', models.PositiveIntegerField(default=0)),
                ('late_submission_penalty_percent', models.PositiveIntegerField(default=0)),
                ('is_graded', models.BooleanField(default=True)),
                ('shuffle_questions', models.BooleanField(default=False)),
                ('central_source_id', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('local_id', models.CharField(default=cuid.cuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('allow_late', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityIdRedirect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_id', models.PositiveIntegerField(db_index=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('question_instruction', models.FileField(blank=True, null=True, upload_to=activity.models.activity_model.get_upload_file_instruction)),
                ('correct_answer', models.TextField()),
                ('score', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.TextField(blank=True, default='')),
                ('choice_image', models.ImageField(blank=True, null=True, upload_to=activity.models.activity_model.get_upload_choice_image)),
                ('is_left_side', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='QuizType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Multiple Choice', 'Multiple Choice'), ('Essay', 'Essay'), ('True/False', 'True/False'), ('Fill in the Blank', 'Fill in the Blank'), ('Matching Type', 'Matching Type'), ('Calculated Numeric', 'Calculated Numeric'), ('Document', 'Document'), ('Participation', 'Participation'), ('Direct Score', 'Direct Score')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RetakeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retake_number', models.PositiveIntegerField(default=1)),
                ('score', models.FloatField(default=0)),
                ('retake_time', models.DateTimeField(auto_now_add=True)),
                ('duration', models.PositiveIntegerField(default=0)),
                ('question_order', models.JSONField(blank=True, default=list)),
                ('choice_order', models.JSONField(blank=True, default=dict)),
                ('last_index', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('ongoing', 'Ongoing'), ('submitted', 'Submitted'), ('expired', 'Expired'), ('in_progress', 'In_progress')], default='ongoing', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('will_end_at', models.DateTimeField(blank=True, null=True)),
                ('local_id', models.CharField(blank=True, max_length=36, null=True)),
                ('last_heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('total_elapsed_seconds', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='RetakeRecordDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_answer', models.TextField(blank=True, null=True)),
                ('score', models.FloatField(default=0)),
                ('submission_time', models.DateTimeField(blank=True, null=True)),
                ('uploaded_file', models.FileField(blank=True, null=True, upload_to=activity.models.retake_models.get_upload_path)),
                ('local_id', models.CharField(blank=True, max_length=36, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rubrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rubric_name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RubricsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='ScoreChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_score', models.FloatField()),
                ('new_score', models.FloatField()),
                ('change_date', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='StudentActivity',
            fields=[
                ('retake_count', models.PositiveIntegerField(default=0)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('total_score', models.FloatField(default=0)),
                ('file', models.FileField(blank=True, null=True, upload_to=activity.models.student_activity_model.get_upload_path_file)),
                ('is_editable', models.BooleanField(default=False, help_text='If enabled, teachers can edit this score. If disabled, only registrars can modify it.')),
                ('attendance_mode', models.CharField(blank=True, choices=[('Present_Online', 'Present_Online'), ('present', 'Present'), ('late', 'Late'), ('excused', 'Excused'), ('Absent', 'Absent')], max_length=15, null=True)),
                ('feedback', models.TextField(blank=True, default='')),
                ('local_id', models.CharField(default=cuid.cuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('activity_local_id', models.CharField(blank=True, max_length=36, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0)),
                ('student_answer', models.TextField(blank=True, null=True)),
                ('uploaded_file', models.FileField(blank=True, null=True, upload_to=activity.models.activity_model.get_upload_path)),
                ('status', models.BooleanField(default=False)),
                ('submission_time', models.DateTimeField(blank=True, default=None, null=True)),
                ('is_participation', models.BooleanField(default=False)),
                ('is_graded', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
    ]
