# Generated by Django 5.0.7 on 2026-05-07 01:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activity', '0001_initial'),
        ('course', '0002_initial'),
        ('module', '0001_initial'),
        ('subject', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='additional_modules',
            field=models.ManyToManyField(blank=True, related_name='additional_activities', to='module.module'),
        ),
        migrations.AddField(
            model_name='activity',
            name='remedial_students',
            field=models.ManyToManyField(blank=True, limit_choices_to={'profile__role__name__iexact': 'Student'}, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activity',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='subject.subject'),
        ),
        migrations.AddField(
            model_name='activity',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.term'),
        ),
        migrations.AddField(
            model_name='activityidredirect',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legacy_redirects', to='activity.activity'),
        ),
        migrations.AddField(
            model_name='activityquestion',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='activity.activity'),
        ),
        migrations.AddField(
            model_name='activityquestion',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='subject.subject'),
        ),
        migrations.AddField(
            model_name='activity',
            name='activity_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='activity.activitytype'),
        ),
        migrations.AddField(
            model_name='questionchoice',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='activity.activityquestion'),
        ),
        migrations.AddField(
            model_name='questionchoice',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='subject.subject'),
        ),
        migrations.AddField(
            model_name='activityquestion',
            name='quiz_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='activity.quiztype'),
        ),
        migrations.AddField(
            model_name='retakerecord',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='activity.activity'),
        ),
        migrations.AddField(
            model_name='retakerecord',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='retakerecorddetail',
            name='activity_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='activity.activityquestion'),
        ),
        migrations.AddField(
            model_name='retakerecorddetail',
            name='retake_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='retake_record_details', to='activity.retakerecord'),
        ),
        migrations.AddField(
            model_name='retakerecorddetail',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rubrics',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='subject.subject'),
        ),
        migrations.AddField(
            model_name='rubrics',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rubricsitem',
            name='activity_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='activity.activityquestion'),
        ),
        migrations.AddField(
            model_name='rubricsitem',
            name='rubric',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='activity.rubrics'),
        ),
        migrations.AddField(
            model_name='scorechangelog',
            name='changed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='score_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentactivity',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='activity.activity'),
        ),
        migrations.AddField(
            model_name='studentactivity',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentactivity',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='subject.subject'),
        ),
        migrations.AddField(
            model_name='studentactivity',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='course.term'),
        ),
        migrations.AddField(
            model_name='scorechangelog',
            name='student_activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_logs', to='activity.studentactivity'),
        ),
        migrations.AddField(
            model_name='retakerecord',
            name='student_activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='retake_records', to='activity.studentactivity'),
        ),
        migrations.AddField(
            model_name='studentquestion',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='activity.activity'),
        ),
        migrations.AddField(
            model_name='studentquestion',
            name='activity_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='activity.activityquestion'),
        ),
        migrations.AddField(
            model_name='studentquestion',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='rubrics',
            unique_together={('subject', 'rubric_name')},
        ),
    ]
