# Generated by Django 5.0.7 on 2026-05-07 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitytype',
            name='display_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='quiztype',
            name='display_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
