# Generated by Django 5.0.7 on 2026-05-15 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0004_relabel_participation_to_major_assessment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='max_score',
            field=models.FloatField(blank=True, default=100, null=True),
        ),
    ]
