# Generated by Django 5.0.7 on 2026-05-18 03:21

import cuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0005_alter_activity_max_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retakerecord',
            name='local_id',
            field=models.CharField(db_index=True, default=cuid.cuid, editable=False, max_length=36, unique=True),
        ),
        migrations.AlterField(
            model_name='retakerecorddetail',
            name='local_id',
            field=models.CharField(db_index=True, default=cuid.cuid, editable=False, max_length=36, unique=True),
        ),
    ]
