# Generated by Django 5.0.7 on 2026-05-22 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0008_backfill_studentquestion_into_retake'),
    ]

    operations = [
        migrations.AddField(
            model_name='retakerecord',
            name='late_penalty_percent',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
