# Generated by Django 5.0.7 on 2026-05-20 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IDMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=64)),
                ('model_name', models.CharField(max_length=64)),
                ('old_pk', models.CharField(max_length=64)),
                ('new_pk', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['app_label', 'model_name', 'old_pk'], name='migration_i_app_lab_fbbf14_idx')],
                'unique_together': {('app_label', 'model_name', 'old_pk')},
            },
        ),
        migrations.CreateModel(
            name='MigrationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=64)),
                ('model_name', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('paused', 'Paused'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('last_cursor', models.CharField(blank=True, default='', max_length=128)),
                ('total_estimated', models.IntegerField(default=0)),
                ('rows_fetched', models.IntegerField(default=0)),
                ('rows_written', models.IntegerField(default=0)),
                ('rows_skipped', models.IntegerField(default=0)),
                ('rows_errored', models.IntegerField(default=0)),
                ('dry_run', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_verification', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['app_label', 'model_name'],
                'indexes': [models.Index(fields=['status'], name='migration_m_status_4ee223_idx')],
                'unique_together': {('app_label', 'model_name')},
            },
        ),
        migrations.CreateModel(
            name='MigrationRunLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('cursor_in', models.CharField(blank=True, default='', max_length=128)),
                ('cursor_out', models.CharField(blank=True, default='', max_length=128)),
                ('rows_in_page', models.IntegerField(default=0)),
                ('rows_written', models.IntegerField(default=0)),
                ('rows_skipped', models.IntegerField(default=0)),
                ('rows_errored', models.IntegerField(default=0)),
                ('http_status', models.IntegerField(blank=True, null=True)),
                ('retry_attempt', models.IntegerField(default=0)),
                ('is_retry', models.BooleanField(default=False)),
                ('is_dry_run', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, default='')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='run_logs', to='migration.migrationjob')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='MigrationErrorRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('old_app', models.CharField(max_length=64)),
                ('old_model', models.CharField(max_length=64)),
                ('old_pk', models.CharField(blank=True, default='', max_length=64)),
                ('batch_cursor', models.CharField(blank=True, default='', max_length=128)),
                ('batch_index', models.IntegerField(blank=True, null=True)),
                ('category', models.CharField(choices=[('transport_error', 'Transport error'), ('auth_error', 'Auth error'), ('throttled', 'Throttled'), ('mapper_error', 'Mapper error'), ('missing_fk', 'Missing FK'), ('validation', 'Validation'), ('db_error', 'DB error'), ('unknown', 'Unknown')], max_length=32)),
                ('message', models.CharField(max_length=500)),
                ('field', models.CharField(blank=True, default='', max_length=120)),
                ('expected', models.CharField(blank=True, default='', max_length=500)),
                ('actual', models.CharField(blank=True, default='', max_length=500)),
                ('source_file', models.CharField(blank=True, default='', max_length=255)),
                ('source_line', models.IntegerField(blank=True, null=True)),
                ('source_function', models.CharField(blank=True, default='', max_length=120)),
                ('traceback', models.TextField(blank=True, default='')),
                ('payload_excerpt', models.JSONField(blank=True, default=dict)),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.TextField(blank=True, default='')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='migration.migrationjob')),
                ('run_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='migration.migrationrunlog')),
            ],
            options={
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.AddIndex(
            model_name='migrationrunlog',
            index=models.Index(fields=['job', '-started_at'], name='migration_m_job_id_853c48_idx'),
        ),
        migrations.AddIndex(
            model_name='migrationerrorrecord',
            index=models.Index(fields=['job', 'category'], name='migration_m_job_id_b7b68b_idx'),
        ),
        migrations.AddIndex(
            model_name='migrationerrorrecord',
            index=models.Index(fields=['resolved', 'category'], name='migration_m_resolve_3445ae_idx'),
        ),
        migrations.AddIndex(
            model_name='migrationerrorrecord',
            index=models.Index(fields=['-occurred_at'], name='migration_m_occurre_e471c2_idx'),
        ),
    ]
