# Generated by Django 5.0.7 on 2026-05-20 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegacyAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_app', models.CharField(max_length=64)),
                ('source_model', models.CharField(max_length=64)),
                ('source_pk', models.CharField(max_length=64)),
                ('occurred_at', models.DateTimeField(blank=True, null=True)),
                ('payload', models.JSONField(default=dict)),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['source_app', 'source_model', '-occurred_at'], name='migration_l_source__c97d4b_idx'), models.Index(fields=['source_app', 'source_model', 'source_pk'], name='migration_l_source__e152fc_idx')],
                'unique_together': {('source_app', 'source_model', 'source_pk')},
            },
        ),
    ]
