# Generated by Django 5.0.7 on 2026-05-07 01:44

import django.db.models.deletion
import multiselectfield.db.fields
import subject.models.sdg_models
import subject.models.subject_model
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SDG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('photo', models.ImageField(upload_to=subject.models.sdg_models.get_upload_path_sdg)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=200)),
                ('subject_descriptive_title', models.CharField(blank=True, max_length=100, null=True)),
                ('subject_short_name', models.CharField(blank=True, max_length=30, null=True)),
                ('subject_photo', models.ImageField(blank=True, null=True, upload_to=subject.models.subject_model.get_upload_path)),
                ('allow_substitute_teacher', models.BooleanField(default=False)),
                ('subject_description', models.TextField(blank=True, null=True)),
                ('subject_code', models.CharField(blank=True, max_length=30, null=True)),
                ('room_number', models.CharField(blank=True, max_length=30, null=True)),
                ('unit', models.PositiveIntegerField(default=3)),
                ('is_coil', models.BooleanField(default=False)),
                ('is_hali', models.BooleanField(default=False)),
                ('is_cte', models.BooleanField(default=False)),
                ('max_number_of_enrollees', models.BigIntegerField(blank=True, null=True)),
                ('number_of_enrollees', models.BigIntegerField(blank=True, default=0, null=True)),
                ('duration', models.CharField(blank=True, max_length=200, null=True)),
                ('industry_partners', models.CharField(blank=True, max_length=250, null=True)),
                ('highlight', models.TextField(blank=True, null=True)),
                ('subject_sync_id', models.CharField(blank=True, max_length=200, null=True)),
                ('subject_type', models.CharField(blank=True, choices=[('Lec', 'Lec'), ('Lab', 'Lab')], max_length=200, null=True)),
                ('status', models.CharField(choices=[('Ongoing', 'Ongoing'), ('Available', 'Available'), ('Closed', 'Closed')], default='Available', max_length=10)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('issued_by', models.CharField(blank=True, max_length=200, null=True)),
                ('issued_under', models.CharField(blank=True, max_length=200, null=True)),
                ('issued_on', models.DateField(blank=True, null=True)),
                ('assign_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='primary_teacher', to=settings.AUTH_USER_MODEL)),
                ('collaborators', models.ManyToManyField(blank=True, help_text='Other teachers who can help manage the subject.', related_name='subject_collaborations', to=settings.AUTH_USER_MODEL)),
                ('substitute_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='substitute_teacher', to=settings.AUTH_USER_MODEL)),
                ('target_sdgs', models.ManyToManyField(blank=True, to='subject.sdg')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_type', models.CharField(blank=True, choices=[('Overload', 'Overload'), ('Build in', 'Build in'), ('Regular', 'Regular')], max_length=20, null=True)),
                ('sync_id', models.CharField(blank=True, max_length=200, null=True)),
                ('schedule_start_time', models.TimeField()),
                ('schedule_end_time', models.TimeField()),
                ('days_of_week', multiselectfield.db.fields.MultiSelectField(choices=[('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday'), ('Sun', 'Sunday')], max_length=100)),
                ('is_active_semester', models.BooleanField(default=True)),
                ('semester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='course.semester')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='subject.subject')),
            ],
        ),
        migrations.CreateModel(
            name='EvaluationAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_visible', models.BooleanField(default=False)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.semester')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_evaluations', to=settings.AUTH_USER_MODEL)),
                ('questions', models.ManyToManyField(related_name='assignments', to='subject.evaluationquestion')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject.subject')),
            ],
            options={
                'verbose_name': 'Evaluation Assignment',
                'verbose_name_plural': 'Evaluation Assignments',
            },
        ),
        migrations.CreateModel(
            name='SubjectCollaborator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('invited_at', models.DateTimeField(auto_now_add=True)),
                ('accepted', models.BooleanField(default=False)),
                ('token', models.UUIDField(blank=True, default=uuid.uuid4, null=True, unique=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborator_invites', to='subject.subject')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('general_feedback', models.TextField(blank=True, null=True)),
                ('assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='subject.evaluationassignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherEvaluationResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField()),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='subject.teacherevaluation')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject.evaluationquestion')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectGradeFinalization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_finalized', models.BooleanField(default=False)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('finalized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.semester')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject.subject')),
            ],
            options={
                'verbose_name': 'Subject Grade Finalization',
                'verbose_name_plural': 'Subject Grade Finalizations',
                'unique_together': {('subject', 'semester')},
            },
        ),
    ]
