# Generated by Django 5.0.7 on 2026-05-08 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='self_attendance_enabled',
            field=models.BooleanField(default=False, help_text='Allow enrolled students to mark their own attendance during scheduled class time.'),
        ),
    ]
