# Generated by Django 5.0.7 on 2026-05-12 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0002_subject_self_attendance_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='quest_count_per_lesson',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
