# Generated by Django 5.0.7 on 2026-05-07 01:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0002_initial'),
        ('subject', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BadgeDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('tier', models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum'), ('hidden', 'Hidden'), ('seasonal', 'Seasonal')], max_length=20)),
                ('icon', models.CharField(max_length=50)),
                ('target_role', models.CharField(default='student', max_length=20)),
                ('criteria_json', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherBadgeDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('tier', models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum')], max_length=20)),
                ('icon', models.CharField(max_length=50)),
                ('criteria_json', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('challenge_type', models.CharField(choices=[('rotating', 'Rotating'), ('milestone', 'Milestone')], max_length=20)),
                ('criteria_json', models.JSONField(default=dict)),
                ('ip_reward', models.PositiveIntegerField()),
                ('duration_days', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CodingStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_submissions', models.PositiveIntegerField(default=0)),
                ('perfect_submissions', models.PositiveIntegerField(default=0)),
                ('total_katas', models.PositiveIntegerField(default=0)),
                ('perfect_katas', models.PositiveIntegerField(default=0)),
                ('languages_used', models.JSONField(default=list)),
                ('fast_perfects', models.PositiveIntegerField(default=0)),
                ('current_streak', models.PositiveIntegerField(default=0)),
                ('best_streak', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coding_stats', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SideActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_type', models.CharField(choices=[('daily_challenge', 'Daily Challenge'), ('flashcard', 'Flashcard Review'), ('speed_round', 'Speed Round'), ('match_pair', 'Match Pair'), ('fill_blank', 'Fill in the Blank'), ('drag_order', 'Drag to Order'), ('word_scramble', 'Word Scramble'), ('equation_balance', 'Equation Balancer'), ('math_drill', 'Math Drill'), ('geo_map', 'Geography Map'), ('timeline_sort', 'Timeline Sort'), ('code_kata', 'Code Kata'), ('typing_drill', 'Typing Drill'), ('reading_mini', 'Reading Comprehension Mini'), ('practice_quiz', 'Practice Quiz')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('content_json', models.JSONField()),
                ('estimated_minutes', models.PositiveSmallIntegerField(default=3)),
                ('xp_reward', models.PositiveSmallIntegerField(default=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='side_activities', to='subject.subject')),
            ],
        ),
        migrations.CreateModel(
            name='SideActivityAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.FloatField(null=True)),
                ('time_taken_seconds', models.PositiveIntegerField(null=True)),
                ('xp_awarded', models.PositiveSmallIntegerField(default=0)),
                ('details_json', models.JSONField(default=dict)),
                ('side_activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamification.sideactivity')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='side_activity_attempts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('progress_percent', models.PositiveSmallIntegerField(default=100)),
                ('award_reason', models.CharField(blank=True, default='', max_length=300)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('awarded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manually_awarded_badges', to=settings.AUTH_USER_MODEL)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamification.badgedefinition')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earned_badges', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentGamification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_xp', models.PositiveIntegerField(default=0)),
                ('current_level', models.PositiveIntegerField(default=1)),
                ('login_streak', models.PositiveIntegerField(default=0)),
                ('submission_streak', models.PositiveIntegerField(default=0)),
                ('accuracy_streak', models.PositiveIntegerField(default=0)),
                ('streak_freezes_available', models.PositiveSmallIntegerField(default=1)),
                ('last_active_date', models.DateField(blank=True, null=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gamification', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('progress_percent', models.PositiveSmallIntegerField(default=100)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earned_teacher_badges', to=settings.AUTH_USER_MODEL)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamification.teacherbadgedefinition')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherChallengeProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('current_value', models.PositiveIntegerField(default=0)),
                ('target_value', models.PositiveIntegerField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamification.teacherchallenge')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_progress', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherGamification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_ip', models.PositiveIntegerField(default=0)),
                ('current_rank', models.CharField(default='bronze_mentor', max_length=30)),
                ('rank_tier', models.CharField(default='bronze', max_length=20)),
                ('rank_title', models.CharField(default='Mentor', max_length=30)),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_gamification', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_given', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_received', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherRecognition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=300)),
                ('xp_awarded', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recognitions_received', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recognitions_given', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='XPTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('reason', models.CharField(max_length=100)),
                ('source_type', models.CharField(max_length=50)),
                ('source_id', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xp_transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IPTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('reason', models.CharField(max_length=100)),
                ('source_type', models.CharField(max_length=50)),
                ('source_id', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ip_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['teacher', 'created_at'], name='gam_ip_teacher_date_idx'), models.Index(fields=['source_type', 'source_id'], name='gam_ip_src_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='sideactivity',
            index=models.Index(fields=['subject', 'sub_type'], name='gamificatio_subject_01e333_idx'),
        ),
        migrations.AddIndex(
            model_name='sideactivityattempt',
            index=models.Index(fields=['student', 'completed_at'], name='gamificatio_student_30144b_idx'),
        ),
        migrations.AddIndex(
            model_name='sideactivityattempt',
            index=models.Index(fields=['side_activity'], name='gamificatio_side_ac_870198_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='studentbadge',
            unique_together={('student', 'badge')},
        ),
        migrations.AddIndex(
            model_name='studentgamification',
            index=models.Index(fields=['-total_xp'], name='gam_total_xp_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='teacherbadge',
            unique_together={('teacher', 'badge')},
        ),
        migrations.AlterUniqueTogether(
            name='teacherchallengeprogress',
            unique_together={('teacher', 'challenge', 'started_at')},
        ),
        migrations.AddIndex(
            model_name='teachergamification',
            index=models.Index(fields=['-total_ip'], name='gam_teacher_ip_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='teacherrating',
            unique_together={('teacher', 'student', 'semester')},
        ),
        migrations.AddIndex(
            model_name='xptransaction',
            index=models.Index(fields=['student', 'created_at'], name='gam_xp_stu_date_idx'),
        ),
        migrations.AddIndex(
            model_name='xptransaction',
            index=models.Index(fields=['source_type', 'source_id'], name='gam_xp_src_idx'),
        ),
    ]
