# Generated by Django 5.0.7 on 2026-05-07 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xptransaction',
            name='source_id',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
    ]
