# Generated by Django 5.0.7 on 2026-05-12 08:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0003_studentbadge_share_token'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationQuestSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_mode_enabled', models.BooleanField(default=True)),
                ('manual_mode_enabled', models.BooleanField(default=True)),
                ('upload_mode_enabled', models.BooleanField(default=True)),
                ('ai_provider', models.CharField(choices=[('anthropic', 'Anthropic'), ('openai', 'OpenAI')], default='anthropic', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Organization Quest Settings',
                'verbose_name_plural': 'Organization Quest Settings',
            },
        ),
    ]
